### ISSUE TITLE
New topic: args, kwargs

### ISSUE THREAD

**Issue by gsemet** [wilfredinni/python-cheatsheet#11]

**Comment by wilfredinni** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/R5AmgBSr/1-test)

**Comment by wilfredinni** [comment]
This topic was added by @Sonatrix 

Thank you!

**Comment by gsemet** [comment]
hum, my remark about mixin args+kwargs has been taken into account :(
