### ISSUE TITLE
Please include "Requests" Library

### ISSUE THREAD

**Issue by KK4HFJ** [wilfredinni/python-cheatsheet#141]
"Requests" is a common topic in technical interviews, where you have to share your screen and retrieve data from a public API. Would be helpful for many to have it on the cheat sheet.

**Comment by wilfredinni** [comment]
Hi! For now, the focus is on modules from the standard library only. That being said, their [documentation](https://requests.readthedocs.io/en/latest/) is excellent and beginner-friendly, I'm pretty sure you will find there everything you want to know.
