### ISSUE TITLE
Typo in Python String Formatting

### ISSUE THREAD

**Issue by jkornijchuk** [wilfredinni/python-cheatsheet#142]
I guess there is a typo in the article. You used %x instead of %d
the %d format specifier is used to convert an int value to a string, while %x helps to format the hexadecimal representation of the integer.

![image](https://user-images.githubusercontent.com/50628551/201172458-1fed0af3-71f9-4a55-b101-628ed22ff0a4.png)

**Comment by wilfredinni** [comment]
Hey, thank you for that.
