### ISSUE TITLE
.title() method missing from Manipulating strings

### ISSUE THREAD

**Issue by elp3dr0** [wilfredinni/python-cheatsheet#145]
.title() method is missing from the Maniupulating Strings section of the cheatsheet.

Current situation:
Title is only referenced by way of the istitle() method in the IsX section. I.e. no reference to string.title() method.
Contrast this with methods for upper and lower, both of which have sections for .isupper()/islower() and .upper()/.lower().

Expected behaviour:
string.title() explicitly explained in the Manipulating Strings section of the cheatsheet.
E.g. Include string.title() in the same box as upper() and lower() methods. In which case it would also probably make sense to pull istitle() out of the IsX box and instead include it alongside isupper() and islower() for consistency.

**Comment by wilfredinni** [comment]
Hey, thank you! I just added the title method now
