### ISSUE TITLE
OOP Basics?

### ISSUE THREAD

**Issue by jonathanhle** [wilfredinni/python-cheatsheet#162]
Would a section on OOP basics be worthy or too much content for the cheatsheet?
 - Define a Class in Python
 - Instantiate an Object
 - Inherit From Other Classes
 - Calling Methods

**Comment by wilfredinni** [comment]
Hey! It's been in the backlog for a while now, I hope I can find the time soon. PR are welcome too!

**Comment by noraa-july-stoke** [comment]
Hey I will try to get on this!
