### ISSUE TITLE
Add copy module

### ISSUE THREAD

**Issue by wilfredinni** [wilfredinni/python-cheatsheet#215]
https://docs.python.org/3/library/copy.html

**Comment by madhurimozara** [comment]
Do we need to add separate page for Copy Module in cheatsheet document or need to integrate in functions or somewhere else?

**Comment by wilfredinni** [comment]
Hi! yes you need a new md file under docs/modules

**Comment by MozarM** [comment]
Ok, Thank you. I started working on it. Can you please assign it to me.

**Comment by MozarM** [comment]
Hello, Please find the PR is created for the Copy Module - [https://github.com/wilfredinni/python-cheatsheet/pull/277](https://github.com/wilfredinni/python-cheatsheet/pull/277 )

**Comment by wilfredinni** [comment]
> Hello, Please find the PR is created for the Copy Module - #277

Merged!
