### ISSUE TITLE
String Formatting

### ISSUE THREAD

**Issue by JDiPierro** [wilfredinni/python-cheatsheet#3]
This is awesome :) I don't see any mention of String Formatting though. I think it'd be useful to have this right by the String Concatenation since it should preferred over chaining concatenations for more complex strings.

```
key = "foo"
value = "bar"

baz = "{}: {}".format(key, value)
baz = "First value: {0}, Second value: {1}".format(key, value)
baz = "key: {key}, value: {value}".format(key=key, value=value)
```

The `.format` method should be used over the `%` formatting syntax for compatibility with Python 3. A notable exception is logging. In the `Logging` section you have the following line:

```
logging.debug('Start of factorial(%s)' % (n))
```

This is a total micro-optimization but doing this causes the string formatting to occur even if the log level isn't debug. You can skip the formatting and pass the variables as extra arguments and the logging library will automatically format the message before printing:

```
logging.debug('Start of factorial(%s)', n)
```

However in that case only the `%` formatting syntax is supported in Python 2.

**Comment by wilfredinni** [comment]
I was thinkin to add `.format()`, the `Template` form the `string` library and the `Formatted String Literal`. I think it's good to have all the options.

**Comment by wilfredinni** [comment]
Done.

**Comment by JDiPierro** [comment]
Awesome! I didn't know about `from string import Template`
