### ISSUE TITLE
Missing parentheses

### ISSUE THREAD

**Issue by Sphinxs** [wilfredinni/python-cheatsheet#35]
There are missing parentheses in [Path](https://www.pythoncheatsheet.org/#Handling-File-and-Directory-Paths) examples, in Linux and Mac. If someone just copy and paste on terminal, it doesn't work.

![image](https://user-images.githubusercontent.com/19755014/42735342-85b4b6ce-8828-11e8-9573-f9b098084ae9.png)

**Comment by wilfredinni** [comment]
Thank you for noticing this. Added parentheses.

Have a nice day!

**Comment by Sphinxs** [comment]
Thanks, have a nice day too :satisfied:

I also noticed the identation [here](https://www.pythoncheatsheet.org/#Debugging) Is wrong

![image](https://user-images.githubusercontent.com/19755014/42736215-ac4587e0-8838-11e8-91c2-c4aff98be5b7.png)
