### ISSUE TITLE
UI Enhancement:  Unused Side Component with No Content

### ISSUE THREAD

**Issue by srutiii** [wilfredinni/python-cheatsheet#376]
# Issue Title: Unused Side Component with No Content

## Description
I have identified a small side component in the website that appears to be unused. It is a minimal component with a color but no content. This component might be a candidate for removal or further investigation to determine if it's necessary for the project.

## Component Location
- Visit website
- The component is visible on every 

## Actual Behavior
![Screenshot from 2024-01-21 17-53-37](https://github.com/wilfredinni/python-cheatsheet/assets/90701547/02dbe580-aaf0-45b5-8db9-95f7d8093e5c)
![Screenshot from 2024-01-21 17-56-01](https://github.com/wilfredinni/python-cheatsheet/assets/90701547/a8475cf7-918b-42eb-95be-ebc6d3daa0be)

## Expected Behavior
- The component may contain some topics hyperlinked to a different page.
- The component may be used to give everyday facts.
- If the component has no use it should be removed and a the place should be utilised with something meaningful.

**Comment by asherborntofly** [comment]
I don't think this is the issue. It is a section which is used for Ads via Carbon. This is not a issue. We can close it. I think so.

![issue](https://github.com/wilfredinni/python-cheatsheet/assets/31719742/86947609-c800-4ee3-9cb8-0de7a249f8a3)
