### ISSUE TITLE
Clarifying wording for 'continue Statements'

### ISSUE THREAD

**Issue by AFewMistakesAgo** [wilfredinni/python-cheatsheet#42]
I think there's some ambiguity in the current wording for 'continue Statements'.

Current wording is:

> When the program execution reaches a continue statement, the program execution immediately jumps back to the start of the loop.

To me the ambiguity is that it might be interpreted as saying that the loop starts entirely again as though it had not yet been started.

Less ambiguous might be:

> When the program execution reaches a continue statement, the program execution skips directly to the start of the next iteration of the loop (if there is one or more remaining), bypassing any other code remaining in the current iteration of the loop.

**Comment by Akshima-Ghai** [comment]
The continue statement in Python returns the control to the beginning of the while loop. The continue statement rejects all the remaining statements in the current iteration of the loop and moves the control back to the top of the loop. The continue statement can be used in both while and for loops.
